export const beginnerDifficultyConfig = {
  key: 'beginner',
  builder: {
    operatorGlyphSet: 'classic',
    utilitySkillsBypassBuilder: false,
  },
  stageOrder: [1, 2, 3],
  training: {
    guidedRulePanelVariant: 'default',
    stages: {
      1: {
        id: 1,
        name: 'Stage 1 - Number Kinds',
        tutorialTitle: 'Stage 1 Tutorial',
        clearMessage: 'You beat Stage 1. Stage 2 is open.',
        failMessage: 'Not yet. Check your mistakes and try again.',
      },
      2: {
        id: 2,
        name: 'Stage 2 - Add / Subtract',
        tutorialTitle: 'Stage 2 Tutorial',
        clearMessage: 'You beat Stage 2. Stage 3 is open.',
        failMessage: 'Not yet. Try again until you get {passScore}/{total} right.',
      },
      3: {
        id: 3,
        name: 'Stage 3 - Guided Battle',
        tutorialTitle: 'Stage 3 Tutorial',
        clearMessage: 'Beginner is done! You know the basics now. Try Medium next.',
        failMessage: 'You lost the battle. Read the message and try Stage 3 again.',
        battle: {
          enemyDataKey: 'trainingDummy',
          enemyKey: 'training_stage3',
          winKey: 'training_stage3',
        },
      },
    },
    guidedBattle: {
      battleId: 'training_stage3',
      enemyKey: 'training_stage3',
      allowedCommands: ['fight'],
      allowedSkillIds: ['evenAttack'],
      lockBackToRun: true,
      lockBuilderBack: true,
      requiredRuleLabel: 'even',
      helperTexts: {
        mainFightSelected: 'Step 1: Choose Fight. Monster rule: {rule}.',
        mainOtherSelected: 'Use Fight in this lesson. Bag and Run are locked.',
        skillCorrect: 'Step 2: Good. Press Enter on {skill}.',
        skillWrong: 'Use {skill}. This monster needs a {rule} answer.',
        builder: 'Step 3: Make a {rule} answer. Press Enter.',
        dialog: 'Read the battle message. Press Enter.',
        fallback: 'Choose Fight. Use {skill}. Make a {rule} answer.',
        lockedBag: 'Bag is locked in this lesson. Choose Fight.',
        lockedRun: 'Run is locked in this lesson. Choose Fight.',
        lockedBack: 'Stay in the lesson. Choose Fight.',
        lockedBuilderBack: 'Stay here. Make a {rule} answer first.',
        wrongSkill: 'Use {skill}. This monster needs a {rule} answer.',
        incompleteBuilder: 'Fill all 3 boxes first. Then make a {rule} answer.',
      },
    },
  },
};
