export const audioKeys = {
  bgm: {
    normal: 'bgmNormal',
    dungeon: 'bgmDungeon',
    battle: 'bgmBattle',
    bossBattle: 'bgmBossBattle',
  },
  sfx: {
    uiMove: 'sfxUiMove',
    uiConfirm: 'sfxUiConfirm',
    uiBack: 'sfxUiBack',
    answerCorrect: 'sfxAnswerCorrect',
    answerWrong: 'sfxAnswerWrong',
    playerAttack: 'sfxPlayerAttack',
    enemyHit: 'sfxEnemyHit',
    playerHit: 'sfxPlayerHit',
    blocked: 'sfxBlocked',
    enemyDefeat: 'sfxEnemyDefeat',
    victory: 'sfxVictory',
    levelUp: 'sfxLevelUp',
    playerMove: 'sfxPlayerMove',
    buff: 'sfxBuff',
    debuff: 'sfxDebuff',
    run: 'sfxRun',
    potion: 'sfxPotion',
    shopPurchase: 'sfxShopPurchase',
    actionFail: 'sfxActionFail',
  },
};

export const audioPaths = {
  bgm: {
    [audioKeys.bgm.normal]: 'assets/audio/bgm/bgm_normal.mp3',
    [audioKeys.bgm.dungeon]: 'assets/audio/bgm/bgm_dungeon.mp3',
    [audioKeys.bgm.battle]: 'assets/audio/bgm/bgm_battle.mp3',
    [audioKeys.bgm.bossBattle]: 'assets/audio/bgm/bgm_boss_battle.mp3',
  },
  sfx: {
    [audioKeys.sfx.uiMove]: 'assets/audio/sfx/ui_move.mp3',
    [audioKeys.sfx.uiConfirm]: 'assets/audio/sfx/ui_confirm.mp3',
    [audioKeys.sfx.uiBack]: 'assets/audio/sfx/ui_back.mp3',
    [audioKeys.sfx.answerCorrect]: 'assets/audio/sfx/answer_correct.mp3',
    [audioKeys.sfx.answerWrong]: 'assets/audio/sfx/answer_wrong.mp3',
    [audioKeys.sfx.playerAttack]: 'assets/audio/sfx/player_attack.mp3',
    [audioKeys.sfx.enemyHit]: 'assets/audio/sfx/enemy_hit.mp3',
    [audioKeys.sfx.playerHit]: 'assets/audio/sfx/player_hit.mp3',
    [audioKeys.sfx.blocked]: 'assets/audio/sfx/blocked.mp3',
    [audioKeys.sfx.enemyDefeat]: 'assets/audio/sfx/enemy_defeat.mp3',
    [audioKeys.sfx.victory]: 'assets/audio/sfx/victory.mp3',
    [audioKeys.sfx.levelUp]: 'assets/audio/sfx/level_up.mp3',
    [audioKeys.sfx.playerMove]: 'assets/audio/sfx/player_move.mp3',
    [audioKeys.sfx.buff]: 'assets/audio/sfx/buff.mp3',
    [audioKeys.sfx.debuff]: 'assets/audio/sfx/debuff.mp3',
    [audioKeys.sfx.run]: 'assets/audio/sfx/run.mp3',
    [audioKeys.sfx.potion]: 'assets/audio/sfx/potion.mp3',
    [audioKeys.sfx.shopPurchase]: 'assets/audio/sfx/sfx_shop_purchase.mp3',
    [audioKeys.sfx.actionFail]: 'assets/audio/sfx/action_fail.mp3',
  },
};
